services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: context_extractor_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: context_extractor
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d:ro

volumes:
  data:
